"""Tests for CLUE's metric layer, its checks, and the handoff link contract."""

import unittest

import pandas as pd

from data.metrics import (
    DEFAULT_END,
    DEFAULT_START,
    WINDOW_DAYS,
    WINDOW_LABEL,
    compute_baseline,
    failed_checks,
    node_values,
    reference_period,
    run_checks,
)


class TestReferencePeriod(unittest.TestCase):
    """
    The period arrives on the handoff link.

    A malformed link must fall back rather than raise: it is generated by
    another app, and a study session should not die on a bad URL.
    """

    def test_defaults_match_the_dashboard(self):
        self.assertEqual(reference_period({}), (DEFAULT_START, DEFAULT_END))

    def test_reads_the_link(self):
        self.assertEqual(
            reference_period({"start": "2022-01", "end": "2022-03"}),
            (pd.Period("2022-01", freq="M"), pd.Period("2022-03", freq="M")),
        )

    def test_half_a_period_falls_back(self):
        self.assertEqual(
            reference_period({"start": "2022-01"}), (DEFAULT_START, DEFAULT_END)
        )

    def test_unparseable_period_falls_back(self):
        self.assertEqual(
            reference_period({"start": "banana", "end": "2022-03"}),
            (DEFAULT_START, DEFAULT_END),
        )

    def test_reversed_period_is_put_back_in_order(self):
        self.assertEqual(
            reference_period({"start": "2022-06", "end": "2022-01"}),
            (pd.Period("2022-01", freq="M"), pd.Period("2022-06", freq="M")),
        )


class TestBaselineAgainstRealData(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.baseline = compute_baseline()
        if cls.baseline.is_fallback:
            raise unittest.SkipTest(
                "modeled data source not built; run `python -m datasource.build` "
                "from baseline_dashboard/"
            )

    def test_window_is_ninety_days(self):
        self.assertEqual(WINDOW_DAYS, 90)
        self.assertEqual(WINDOW_LABEL, "90-Day")
        self.assertEqual(self.baseline.window_label, "90-Day")

    def test_headline_describes_the_last_month_in_the_period(self):
        """The same rule the dashboard's KPI cards apply."""
        self.assertEqual(self.baseline.cohort_label, "Jun 2024")
        self.assertEqual(self.baseline.by_month[-1].month_label, "Jun 2024")
        self.assertTrue(self.baseline.by_month[-1].is_focus)

    def test_exactly_one_month_is_highlighted(self):
        focused = [point for point in self.baseline.by_month if point.is_focus]
        self.assertEqual(len(focused), 1)

    def test_chart_spans_the_whole_period(self):
        self.assertEqual(len(self.baseline.by_month), 6)
        self.assertEqual(self.baseline.by_month[0].month_label, "Jan 2024")

    def test_chart_is_in_chronological_order(self):
        keys = [point.sort_key for point in self.baseline.by_month]
        self.assertEqual(keys, sorted(keys))

    def test_all_checks_pass(self):
        for result in run_checks(self.baseline):
            self.assertTrue(result.passed, f"{result.name}: {result.detail}")
        self.assertEqual(failed_checks(self.baseline), [])

    def test_non_purchasers_are_in_the_denominator(self):
        self.assertGreater(
            self.baseline.acquired_users, self.baseline.purchasing_customers
        )

    def test_every_provenance_node_has_a_value(self):
        values = node_values(self.baseline)
        self.assertEqual(len(values), 10)
        for node_id, text in values.items():
            self.assertTrue(text and text != "nan", f"{node_id} formatted as {text!r}")


class TestAgreesWithTheDashboard(unittest.TestCase):
    """
    The whole point of the handoff: CLUE must explain the number the
    participant just clicked, not a different one computed the same way.
    """

    @classmethod
    def setUpClass(cls):
        import sys
        from pathlib import Path

        dashboard = Path(__file__).resolve().parents[2] / "baseline_dashboard"
        if not (dashboard / "metrics" / "compute.py").exists():
            raise unittest.SkipTest("baseline_dashboard not available")
        sys.path.insert(0, str(dashboard))

        try:
            from datasource.loader import load_customers, load_window_facts
            from metrics.compute import CohortFilter, compute

            cls.dashboard_metrics = compute(
                load_customers(), load_window_facts(),
                CohortFilter(DEFAULT_START, DEFAULT_END),
            )
        except Exception as exc:  # data not built
            raise unittest.SkipTest(f"modeled data unavailable: {exc}")
        finally:
            sys.path.remove(str(dashboard))

        cls.clue_baseline = compute_baseline(DEFAULT_START, DEFAULT_END)

    def test_same_cohort_month(self):
        self.assertEqual(
            self.clue_baseline.cohort_label, self.dashboard_metrics.latest.label
        )

    def test_same_headline(self):
        self.assertAlmostEqual(
            self.clue_baseline.customer_value,
            self.dashboard_metrics.customer_value,
            places=9,
        )

    def test_same_base_counts(self):
        self.assertEqual(
            self.clue_baseline.acquired_users, self.dashboard_metrics.acquired_users
        )
        self.assertEqual(
            self.clue_baseline.purchasing_customers,
            self.dashboard_metrics.purchasing_customers,
        )
        self.assertEqual(
            self.clue_baseline.total_orders, self.dashboard_metrics.total_orders
        )
        self.assertAlmostEqual(
            self.clue_baseline.total_gross_order_value,
            self.dashboard_metrics.total_gross_order_value,
            places=2,
        )

    def test_same_factors(self):
        for attribute in (
            "conversion_rate",
            "orders_per_purchasing_customer",
            "average_order_value",
        ):
            with self.subTest(factor=attribute):
                self.assertAlmostEqual(
                    getattr(self.clue_baseline, attribute),
                    getattr(self.dashboard_metrics, attribute),
                    places=9,
                )

    def test_same_chart_series(self):
        """CLUE shows the chart the participant just left, bar for bar."""
        theirs = list(self.dashboard_metrics.by_month.customer_value)
        ours = [point.customer_value for point in self.clue_baseline.by_month]
        self.assertEqual(len(ours), len(theirs))
        for mine, other in zip(ours, theirs):
            self.assertAlmostEqual(mine, other, places=9)

    def test_a_different_period_still_agrees(self):
        """The link can carry any period, so the agreement cannot be a fluke."""
        import sys
        from pathlib import Path

        dashboard = Path(__file__).resolve().parents[2] / "baseline_dashboard"
        sys.path.insert(0, str(dashboard))
        try:
            from datasource.loader import load_customers, load_window_facts
            from metrics.compute import CohortFilter, compute

            start = pd.Period("2022-01", freq="M")
            end = pd.Period("2022-03", freq="M")
            theirs = compute(
                load_customers(), load_window_facts(), CohortFilter(start, end)
            )
        finally:
            sys.path.remove(str(dashboard))

        ours = compute_baseline(start, end)
        self.assertEqual(ours.cohort_label, theirs.latest.label)
        self.assertAlmostEqual(ours.customer_value, theirs.customer_value, places=9)


class TestEmptyPeriod(unittest.TestCase):
    """A period with no acquisitions must degrade quietly, not divide by zero."""

    @classmethod
    def setUpClass(cls):
        cls.baseline = compute_baseline(
            pd.Period("2030-01", freq="M"), pd.Period("2030-03", freq="M")
        )
        if cls.baseline.is_fallback:
            raise unittest.SkipTest("modeled data source not built")

    def test_counts_are_zero(self):
        self.assertEqual(self.baseline.acquired_users, 0)
        self.assertEqual(self.baseline.total_orders, 0)

    def test_ratios_are_nan_not_errors(self):
        self.assertNotEqual(
            self.baseline.customer_value, self.baseline.customer_value
        )

    def test_chart_is_empty_and_has_no_focus(self):
        self.assertEqual(self.baseline.by_month, ())
        self.assertIsNone(self.baseline.focus)


class TestFallback(unittest.TestCase):
    """With no data source, the demo still runs on the reference example."""

    @classmethod
    def setUpClass(cls):
        import os
        from unittest import mock

        with mock.patch.dict(os.environ, {"CLUE_MODELED_DIR": "/nonexistent"}):
            cls.baseline = compute_baseline(DEFAULT_START, DEFAULT_END)

    def test_is_flagged_as_a_fallback(self):
        self.assertTrue(self.baseline.is_fallback)

    def test_still_satisfies_every_check(self):
        for result in run_checks(self.baseline):
            self.assertTrue(result.passed, f"{result.name}: {result.detail}")

    def test_still_has_a_highlighted_month(self):
        self.assertIsNotNone(self.baseline.focus)
        self.assertEqual(self.baseline.focus.month_label, self.baseline.cohort_label)


if __name__ == "__main__":
    unittest.main()
