"""
metrics.py
----------
Every number CLUE displays, computed from the modeled data source.

The metric is **90-Day Customer Value**: the average value generated per
acquired user during their first 90 days after acquisition. It is observed
history, not a prediction.

Two time windows are involved and they are deliberately not merged:

  - the *reference acquisition period* decides which cohort months are in view;
  - the *90-day observation window* is measured from each user's own
    acquisition date, so a user acquired late in a month still gets ninety days
    of follow-up.

Filtering orders by calendar date instead would quietly understate the metric.

CLUE explains **one cohort month**: the most recent month in the reference
period, which is the same month the baseline dashboard's KPI cards report. The
period arrives on the handoff link, so a participant who changed the dashboard's
filter and then clicked through sees the cohort they were actually looking at
rather than a pinned default. Both apps apply the same rule for which month is
the headline, so the two can never disagree about it.

CLUE reads the same Parquet tables the dashboard does, but shares no code with
it -- the two apps stay import-independent.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

import pandas as pd
import streamlit as st

# ---------------------------------------------------------------------------
# Reference acquisition period and observation window
# ---------------------------------------------------------------------------
#
# Matches baseline_dashboard/components/filters.py, so a participant handed over
# by "Open in CLUE" without an explicit period sees the figures they just left.

DEFAULT_START = pd.Period("2024-01", freq="M")
DEFAULT_END = pd.Period("2024-06", freq="M")

# Day 0 is the acquisition day itself, so the window is day offsets 0..89. This
# is not three anniversary months, which is why the month-grain age-facts table
# cannot express it and is not read here.
WINDOW_DAYS = 90
WINDOW_LABEL = f"{WINDOW_DAYS}-Day"

# Query parameters the baseline dashboard puts on the handoff link.
START_PARAM = "start"
END_PARAM = "end"

_DEFAULT_MODELED_DIR = (
    Path(__file__).resolve().parents[2] / "baseline_dashboard" / "data" / "modeled"
)


def modeled_dir() -> Path:
    """Where the modeled Parquet tables live. Override with CLUE_MODELED_DIR."""
    override = os.environ.get("CLUE_MODELED_DIR")
    return Path(override) if override else _DEFAULT_MODELED_DIR


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------

def money(value: float) -> str:
    return f"${value:,.2f}" if abs(value) < 1000 else f"${value:,.0f}"


def whole_money(value: float) -> str:
    return f"${value:,.0f}"


def percent(value: float) -> str:
    return f"{value:.1%}"


def count(value: float) -> str:
    return f"{value:,.0f}"


def decimal(value: float) -> str:
    return f"{value:,.1f}"


def md(text: str) -> str:
    """
    Escape a formatted value for st.markdown.

    Streamlit reads text between two `$` as LaTeX, so a line carrying two money
    values renders as maths with the markup showing through. Escaping the
    dollar signs is the fix; HTML blocks are unaffected and do not need this.
    """
    return text.replace("$", r"\$")


def period_label(start: pd.Period, end: pd.Period) -> str:
    """Human-readable acquisition period, e.g. 'Jan-Jun 2024'."""
    if start == end:
        return start.strftime("%b %Y")
    if start.year == end.year:
        return f"{start.strftime('%b')}-{end.strftime('%b %Y')}"
    return f"{start.strftime('%b %Y')}-{end.strftime('%b %Y')}"


# ---------------------------------------------------------------------------
# The reference period, from the handoff link
# ---------------------------------------------------------------------------

def _parse_month(raw: str | None) -> pd.Period | None:
    """A YYYY-MM query parameter, or None when absent or unparseable."""
    if not raw:
        return None
    try:
        return pd.Period(str(raw), freq="M")
    except (ValueError, TypeError):
        return None


def reference_period(params=None) -> tuple[pd.Period, pd.Period]:
    """
    The acquisition period CLUE is explaining.

    Read from the handoff link, falling back to the dashboard's own default. A
    malformed or half-supplied parameter falls back rather than erroring: the
    link is generated by another app, and a study session should not die on a
    bad URL.
    """
    if params is None:
        try:
            params = st.query_params
        except Exception:  # no Streamlit runtime, e.g. a shell check
            params = {}

    start = _parse_month(params.get(START_PARAM))
    end = _parse_month(params.get(END_PARAM))
    if start is None or end is None:
        return DEFAULT_START, DEFAULT_END
    return (end, start) if start > end else (start, end)


# How far ahead the simulator plans, in months after the cohort being
# explained. The planning goal is worded "over the next 3 months".
FUTURE_MONTHS = 3


def future_window(cohort: pd.Period) -> tuple[pd.Period, pd.Period]:
    """The three acquisition months the simulator is planning for."""
    return cohort + 1, cohort + FUTURE_MONTHS


def _future_acquired_users(
    acquired_by_month: pd.Series, cohort: pd.Period
) -> tuple[int, str]:
    """
    How many users to assume are acquired over the next three months, and the
    label for where that number came from.

    Taken from the same three months a year earlier. Acquisition is seasonal,
    so last quarter's volume is a worse guide to next quarter than the same
    quarter last year is; it is also the only estimate here grounded in
    observed acquisition rather than in a rule of thumb.

    Falls back to repeating the cohort's own size when those months are not in
    the data, which keeps the simulator usable at the edges of the series
    rather than dividing a pathway by zero.
    """
    start, end = future_window(cohort)
    months = [month - 12 for month in pd.period_range(start, end, freq="M")]
    available = [month for month in months if month in acquired_by_month.index]

    if available:
        total = int(acquired_by_month.loc[available].sum())
        if total > 0:
            label = period_label(months[0], months[-1])
            return total, f"same three months a year earlier ({label})"

    cohort_size = int(acquired_by_month.get(cohort, 0))
    return (
        cohort_size * FUTURE_MONTHS,
        f"{FUTURE_MONTHS} x {cohort.strftime('%b %Y')} "
        f"(a year earlier is not in the data)",
    )


# ---------------------------------------------------------------------------
# Baseline metrics
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class MonthPoint:
    """
    One acquisition month in the reference period.

    Drives the overview chart, and -- through the spread of its three factors
    across the period -- the observed ranges shown under the simulator sliders.
    """

    month_label: str
    sort_key: int
    acquired_users: int
    purchasing_customers: int
    customer_value: float
    conversion_rate: float
    orders_per_purchasing_customer: float
    average_order_value: float
    is_focus: bool


@dataclass(frozen=True)
class BaselineMetrics:
    """
    The observed historical baseline for one cohort month.

    The four counts and three factors describe `cohort_label` -- the most recent
    month in the reference period. `by_month` carries every month in the period
    for the overview chart, which is the same chart the participant just left on
    the dashboard.

    Series are plain tuples rather than pandas objects so the whole record stays
    cheap to cache and compare.
    """

    acquired_users: int
    purchasing_customers: int
    total_orders: int
    total_gross_order_value: float

    conversion_rate: float
    orders_per_purchasing_customer: float
    average_order_value: float
    customer_value: float

    by_month: tuple[MonthPoint, ...]

    # How many users the simulator should assume are acquired over the next
    # three months. Taken from the same three months a year earlier, which is
    # the only estimate in the app grounded in observed acquisition rather than
    # in a rule of thumb.
    future_acquired_users: int

    cohort_label: str
    period_label: str
    future_period_label: str
    window: int = WINDOW_DAYS
    is_fallback: bool = False

    @property
    def window_label(self) -> str:
        """'90-Day', the prefix every window-dependent metric name carries."""
        return WINDOW_LABEL

    @property
    def window_days(self) -> int:
        return WINDOW_DAYS

    @property
    def focus(self) -> MonthPoint | None:
        """The charted month the headline describes."""
        for point in self.by_month:
            if point.is_focus:
                return point
        return None

    @property
    def spans_one_month(self) -> bool:
        """Whether the chart has anything to compare the cohort against."""
        return len(self.by_month) <= 1

    def observed_range(self, attribute: str) -> tuple[float, float]:
        """
        Lowest and highest monthly value of one factor across the period.

        Shown under each slider as context, never as a limit: a participant
        exploring "what if a campaign pushed this past anything we have seen?"
        needs to know where that boundary is, not to be stopped at it.
        """
        values = [getattr(point, attribute) for point in self.by_month]
        values = [value for value in values if value == value]  # drop NaN
        if not values:
            return (float("nan"), float("nan"))
        return (min(values), max(values))

    @property
    def observed_best(self) -> tuple[float, float, float]:
        """
        Each factor at its best month in the period.

        A composite, not a month that happened: the three maxima can come from
        three different months. The card that uses it says so.
        """
        return (
            self.observed_range("conversion_rate")[1],
            self.observed_range("orders_per_purchasing_customer")[1],
            self.observed_range("average_order_value")[1],
        )


def _safe_divide(numerator: float, denominator: float) -> float:
    """Ratio, or NaN when the denominator is empty -- never a ZeroDivisionError."""
    return float(numerator) / denominator if denominator else float("nan")


def _from_totals(
    acquired_users: int,
    purchasing_customers: int,
    total_orders: int,
    total_gross_order_value: float,
    by_month: tuple[MonthPoint, ...],
    future_acquired_users: int,
    cohort_label: str,
    label: str,
    future_period_label: str,
    is_fallback: bool = False,
) -> BaselineMetrics:
    """Derive the three factors and the headline from the four base counts."""
    conversion_rate = _safe_divide(purchasing_customers, acquired_users)
    orders_per_purchasing_customer = _safe_divide(total_orders, purchasing_customers)
    average_order_value = _safe_divide(total_gross_order_value, total_orders)

    return BaselineMetrics(
        acquired_users=acquired_users,
        purchasing_customers=purchasing_customers,
        total_orders=total_orders,
        total_gross_order_value=total_gross_order_value,
        conversion_rate=conversion_rate,
        orders_per_purchasing_customer=orders_per_purchasing_customer,
        average_order_value=average_order_value,
        customer_value=conversion_rate
        * orders_per_purchasing_customer
        * average_order_value,
        by_month=by_month,
        future_acquired_users=future_acquired_users,
        cohort_label=cohort_label,
        period_label=label,
        future_period_label=future_period_label,
        is_fallback=is_fallback,
    )


# Used when the modeled data source has not been built, so the demo still runs
# standalone. Every displayed metric is still derived from these rather than
# written out.
_FALLBACK_COUNTS = dict(
    acquired_users=500,
    purchasing_customers=200,
    total_orders=1_000,
    total_gross_order_value=52_000.0,
)


def _fallback_baseline() -> BaselineMetrics:
    """The reference example, shaped like a real six-month period."""
    months = ["Jan 2024", "Feb 2024", "Mar 2024", "Apr 2024", "May 2024", "Jun 2024"]
    values = [88.0, 92.0, 97.0, 101.0, 99.0, 104.0]
    rates = [0.36, 0.38, 0.39, 0.40, 0.39, 0.40]

    orders_each = [4.8, 5.0, 5.1, 5.2, 5.0, 5.3]
    values_each = [9.17, 9.68, 9.76, 10.10, 10.15, 10.40]

    points = tuple(
        MonthPoint(
            month_label=label,
            sort_key=index,
            acquired_users=_FALLBACK_COUNTS["acquired_users"],
            purchasing_customers=_FALLBACK_COUNTS["purchasing_customers"],
            customer_value=value,
            conversion_rate=rate,
            orders_per_purchasing_customer=orders,
            average_order_value=order_value,
            is_focus=index == len(months) - 1,
        )
        for index, (label, value, rate, orders, order_value) in enumerate(
            zip(months, values, rates, orders_each, values_each)
        )
    )
    return _from_totals(
        **_FALLBACK_COUNTS,
        by_month=points,
        future_acquired_users=_FALLBACK_COUNTS["acquired_users"] * FUTURE_MONTHS,
        cohort_label=months[-1],
        label=period_label(DEFAULT_START, DEFAULT_END),
        future_period_label="Jul-Sep 2024",
        is_fallback=True,
    )


def compute_baseline(
    start: pd.Period | None = None,
    end: pd.Period | None = None,
) -> BaselineMetrics:
    """
    Compute the historical baseline from the modeled tables.

    Falls back to the reference example when the data source has not been
    built. Plain function, no Streamlit dependency, so it can be checked from a
    shell.
    """
    if start is None or end is None:
        start, end = reference_period()

    directory = modeled_dir()
    customers_path = directory / "customers.parquet"
    window_path = directory / "customer_window_facts.parquet"

    if not (customers_path.exists() and window_path.exists()):
        return _fallback_baseline()

    customers = pd.read_parquet(
        customers_path, columns=["user_id", "acquisition_month"]
    )
    acquisition_month = pd.PeriodIndex(customers.acquisition_month, freq="M")

    window_facts = pd.read_parquet(
        window_path, columns=["user_id", "orders", "gross_value"]
    )

    # Step 1: attach each acquired user's windowed totals. Users who never
    # ordered inside their own 90 days are absent from window_facts and fill
    # with zeros -- they stay in the denominator, which is what makes the
    # headline "per acquired user" rather than "per customer".
    totals = window_facts.set_index("user_id")
    orders = customers.user_id.map(totals.orders).fillna(0.0)
    gross = customers.user_id.map(totals.gross_value).fillna(0.0)

    frame = pd.DataFrame(
        {
            "acquisition_month": acquisition_month,
            "purchased": (orders.values > 0).astype(int),
            "orders": orders.values,
            "gross_value": gross.values,
        }
    )

    # Acquisition volume across every month in the data, not just the selected
    # ones: the simulator's future estimate reaches a year back from months
    # after the reference period.
    acquired_by_month = frame.groupby("acquisition_month", sort=True).size()

    # Step 2: one row per acquisition month in the reference period.
    in_period = frame[frame.acquisition_month.between(start, end)]
    grouped = in_period.groupby("acquisition_month", sort=True).agg(
        acquired_users=("purchased", "size"),
        purchasing_customers=("purchased", "sum"),
        total_orders=("orders", "sum"),
        total_gross_order_value=("gross_value", "sum"),
    )

    if grouped.empty:
        future_start, future_end = future_window(end)
        return _from_totals(
            acquired_users=0,
            purchasing_customers=0,
            total_orders=0,
            total_gross_order_value=0.0,
            by_month=(),
            future_acquired_users=0,
            cohort_label=end.strftime("%b %Y"),
            label=period_label(start, end),
            future_period_label=period_label(future_start, future_end),
        )

    # Step 3: the headline describes the most recent month in the period -- the
    # same rule the dashboard's KPI cards apply.
    focus_month = grouped.index[-1]
    focus = grouped.loc[focus_month]

    points = tuple(
        MonthPoint(
            month_label=month.strftime("%b %Y"),
            sort_key=month.ordinal,
            acquired_users=int(row.acquired_users),
            purchasing_customers=int(row.purchasing_customers),
            customer_value=_safe_divide(
                row.total_gross_order_value, row.acquired_users
            ),
            conversion_rate=_safe_divide(
                row.purchasing_customers, row.acquired_users
            ),
            orders_per_purchasing_customer=_safe_divide(
                row.total_orders, row.purchasing_customers
            ),
            average_order_value=_safe_divide(
                row.total_gross_order_value, row.total_orders
            ),
            is_focus=month == focus_month,
        )
        for month, row in grouped.iterrows()
    )

    future_users, _ = _future_acquired_users(acquired_by_month, focus_month)
    future_start, future_end = future_window(focus_month)

    return _from_totals(
        acquired_users=int(focus.acquired_users),
        purchasing_customers=int(focus.purchasing_customers),
        total_orders=int(focus.total_orders),
        total_gross_order_value=float(focus.total_gross_order_value),
        by_month=points,
        future_acquired_users=future_users,
        cohort_label=focus_month.strftime("%b %Y"),
        label=period_label(start, end),
        future_period_label=period_label(future_start, future_end),
    )


@st.cache_data(show_spinner=False)
def _load_baseline(start_key: str, end_key: str) -> BaselineMetrics:
    """Cached baseline, parsed once per (period, server process)."""
    return compute_baseline(
        pd.Period(start_key, freq="M"), pd.Period(end_key, freq="M")
    )


def load_baseline() -> BaselineMetrics:
    """The baseline for whatever period the handoff link asked for."""
    start, end = reference_period()
    return _load_baseline(str(start), str(end))


# ---------------------------------------------------------------------------
# Consistency checks
# ---------------------------------------------------------------------------

# Money is rounded to cents at build time, so equality here is approximate by
# construction. A tenth of a cent is tighter than any displayed precision.
TOLERANCE = 1e-3


@dataclass(frozen=True)
class CheckResult:
    name: str
    passed: bool
    detail: str


def _close(a: float, b: float) -> bool:
    if a != a and b != b:  # both NaN
        return True
    return abs(a - b) <= TOLERANCE + TOLERANCE * abs(b)


def run_checks(baseline: BaselineMetrics) -> list[CheckResult]:
    """
    Assert the metric agrees with itself, and with the chart above it.

    If the headline ever disagreed with its own components, or with the bar the
    chart highlights, a study task would be measuring a bug rather than a
    participant, so these are surfaced in the UI rather than logged quietly.
    """
    headline = baseline.customer_value
    product = (
        baseline.conversion_rate
        * baseline.orders_per_purchasing_customer
        * baseline.average_order_value
    )
    simplified = _safe_divide(
        baseline.total_gross_order_value, baseline.acquired_users
    )
    focus = baseline.focus

    results = [
        CheckResult(
            f"{WINDOW_LABEL} Customer Value == conversion x orders per customer x AOV",
            _close(headline, product),
            f"{headline:.6f} vs {product:.6f}",
        ),
        CheckResult(
            f"{WINDOW_LABEL} Customer Value == total gross order value / acquired users",
            _close(headline, simplified),
            f"{headline:.6f} vs {simplified:.6f}",
        ),
        CheckResult(
            "Purchasing Customers == acquired users x conversion rate",
            _close(
                baseline.purchasing_customers,
                baseline.acquired_users * baseline.conversion_rate,
            ),
            f"{baseline.purchasing_customers} vs "
            f"{baseline.acquired_users * baseline.conversion_rate:.6f}",
        ),
        CheckResult(
            "Total Orders == purchasing customers x orders per customer",
            _close(
                baseline.total_orders,
                baseline.purchasing_customers
                * baseline.orders_per_purchasing_customer,
            ),
            f"{baseline.total_orders} vs "
            f"{baseline.purchasing_customers * baseline.orders_per_purchasing_customer:.6f}",
        ),
        CheckResult(
            "Total Gross Order Value == total orders x AOV",
            _close(
                baseline.total_gross_order_value,
                baseline.total_orders * baseline.average_order_value,
            ),
            f"{baseline.total_gross_order_value:.6f} vs "
            f"{baseline.total_orders * baseline.average_order_value:.6f}",
        ),
    ]

    # The chart is the one the participant just left on the dashboard, and the
    # highlighted bar is the month CLUE explains. If those two ever parted
    # company, the handoff would be showing one number and explaining another.
    results.append(
        CheckResult(
            "highlighted month on the chart == the explained cohort",
            focus is not None
            and focus.month_label == baseline.cohort_label
            and _close(focus.customer_value, headline)
            and focus.acquired_users == baseline.acquired_users,
            (
                f"{focus.month_label} {focus.customer_value:.6f}"
                if focus is not None
                else "no highlighted month"
            )
            + f" vs {baseline.cohort_label} {headline:.6f}",
        )
    )

    return results


def failed_checks(baseline: BaselineMetrics) -> list[CheckResult]:
    """Only the checks that did not pass, for the UI banner."""
    return [check for check in run_checks(baseline) if not check.passed]


# ---------------------------------------------------------------------------
# Values keyed by provenance node id
# ---------------------------------------------------------------------------

def node_values(baseline: BaselineMetrics) -> dict[str, str]:
    """Formatted value for each provenance node, for labels and tooltips."""
    return {
        "cust_val": money(baseline.customer_value),
        "conv_rate": percent(baseline.conversion_rate),
        "orders_per_cust": decimal(baseline.orders_per_purchasing_customer),
        "avg_order_val": money(baseline.average_order_value),
        "acq_users": count(baseline.acquired_users),
        "purch_cust_1": count(baseline.purchasing_customers),
        "purch_cust_2": count(baseline.purchasing_customers),
        "tot_orders_1": count(baseline.total_orders),
        "tot_orders_2": count(baseline.total_orders),
        "tot_gross_val": whole_money(baseline.total_gross_order_value),
    }
